// projects.js

const projects = [
  {
    name: "Ashwin's Personal Portfolio",
    image: "./images/portfolioImg.png",
    description: "I have built a personal portfolio website to enhance my frontend skills and showcase my work. Utilizing HTML and Bootstrap, I've crafted an interactive platform to exhibit my projects and abilities. Explore my site to discover my passion for web development and design.",
    usedTech: "HTML,Bootstrap",
    contributorName: "Ashwin Dhangar",
    codeLink: "https://github.com/MrAshwin2142/portfolio/blob/master",
    liveLink: "https://ashwin-portfolioo.netlify.app/#",
  },
  {
    name: "Trae's ecommerce-website",
    image: "./images/traescreenshot.png",
    description: "E-commerce Next.js website built with Typescript and Tailwind CSS, with Local storage backend. meant to emulate store where user can buy favourite football jerseys",
    usedTech: "Typescript, Tailwind CSS",
    contributorName: "Trae Zeeofor",
    codeLink: "https://github.com/traez/ecommerce-website",
    liveLink: "https://ecommerce-website-traez.vercel.app/",
  },
  {
    name: "Moviezz",
    image: "./images/moviezz.png",
    description: "Moviezz is a web application that replicates the Netflix experience, providing real-time movie data and a user-friendly interface for seamless movie and TV show exploration",
    usedTech: "Reactjs",
    contributorName: "Ashwin Dhangar",
    codeLink: "https://github.com/MrAshwin2142/moviezz",
    liveLink: "https://tmdb-moviezz.netlify.app/",
  },
  {
    name: "Text to Emoji",
    image: "https://ashwin-portfolioo.netlify.app/image/TextToEmoji.png",
    description: "Web app using HTML, CSS, and JavaScript, transforming text into emoji-encoded messages. Enhanced user experience with encryption algorithms and an intuitive UI.",
    usedTech: "Javascript",
    contributorName: "Ashwin Dhangar",
    codeLink: "https://github.com/MrAshwin2142/text-to-emoji.github.io",
    liveLink: "https://mrashwin2142.github.io/text-to-emoji.github.io/",
  },
  {
    name: "Soldier Game",
    image: "https://ashwin-portfolioo.netlify.app/image/jsGame.png",
    description: "JavaScript game where a soldier avoids incoming fires, demonstrating real-time interaction and dynamic scoring with animation enhancements.",
    usedTech: "Javascript",
    contributorName: "Ashwin Dhangar",
    codeLink: "https://github.com/MrAshwin2142/soldier.github.io",
    liveLink: "https://mrashwin2142.github.io/soldier.github.io/",
  },
  {
    name: "Thinkrr - socialise and learn",
    image: "images/Dashboard.png",
    description: "This is flask based website where users and students can socialise and grow their career.",
    usedTech: "Flask/Python, HTML, CSS, JS",
    contributorName: "Kunal Achintya Reddy",
    codeLink: "https://github.com/globalnebula/thinkrr",
    liveLink: "",
  },
  {
    name: "Super Market Billing System",
    image: "./images/BillingSystem.jpg",
    description: "Developed a C++ Supermarket Billing System with file handling for efficient product management and data storage, streamlining the billing process",
    usedTech: "C++",
    contributorName: "Ashwin Dhangar",
    codeLink: "https://github.com/MrAshwin2142/Super-Market-Bill-System",
    liveLink: "https://www.linkedin.com/posts/ashwin-dhangar-btech24_cpp-miniproject-project-activity-6979374060145139712-N_EY?utm_source=share&utm_medium=member_desktop",
  },
  {
    name: "Agenda",
    image: "images/Agenda.png",
    description: "Take control of your time and tasks with Agenda, where you can easily structure your day or event schedules in just a few clicks.",
    usedTech: "HTML, CSS, Bootstrap and JavaScript",
    contributorName: "Patrick Ancajas",
    codeLink: "https://github.com/JohnPatrickAncajas/Agenda",
    liveLink: "https://johnpatrickancajas.github.io/Agenda/",
  },
  {
    name: "Timestamp",
    image: "images/Timestamp.png",
    description: "Timestamp is where every second, minute, hour, day, month, and year are elegantly displayed. As you watch the clock tick, find inspiration in quotes that change with the hour and day.",
    usedTech: "HTML, CSS, Bootstrap and JavaScript",
    contributorName: "Patrick Ancajas",
    codeLink: "https://github.com/JohnPatrickAncajas/Timestamp",
    liveLink: "https://johnpatrickancajas.github.io/Timestamp/",
  },
  {
    name: "COMPASS",
    image: "images/COMPASS.png",
    description: "The web page for TUP - COMPASS club.",
    usedTech: "HTML, CSS and JavaScript",
    contributorName: "Patrick Ancajas",
    codeLink: "https://github.com/JohnPatrickAncajas/COMPASS",
    liveLink: "https://johnpatrickancajas.github.io/COMPASS/",
  },
  {
    name: "DeepAm Creation",
    image: "images/deepam.png",
    description: "DeepAm Creations: Your go-to online shop for beautiful flower pots. Shop anytime, anywhere, and elevate your gardening experience.",
    usedTech: "Javascript",
    contributorName: "Akash Yadav",
    codeLink: "https://github.com/Withakash/Deepam-Creation/tree/main",
    liveLink: "https://withakash.github.io/Deepam-Creation/",
  },
    {
    name: "Social Media Handle's",
    image: "images/socialmedia.png",
    description: "One Place to handle all social media accounts link",
    usedTech: "HTML/CSS",
    contributorName: "Akash Yadav",
    codeLink: "https://github.com/Withakash/Social-media",
    liveLink: "https://withakash.github.io/Social-media/",
  },
  {
    name: "Aaryan's Portfolio website",
    image: "images/portfoliosite.png",
    description: "This is my personal portfolio website where I uploads my projects as well as some blogs.",
    usedTech: "NextJs/Sanity",
    contributorName: "Aaryan Patel",
    codeLink: "https://github.com/Aaryan6/portfolio-website-live",
    liveLink: "https://developeraaryan.me",
  },
  {
    name: "AyurvedaGPT",
    image: "images/ayurvedagpt.png",
    description: "This is an AI chatbot trained on Ayurveda knowledge just like the ChatGPT.",
    usedTech: "NextJs/Langchain/Vercel",
    contributorName: "Aaryan Patel",
    codeLink: "https://github.com/Aaryan6/AyurvedaGPT-AIBot",
    liveLink: "https://ayurvedagpt.vercel.app/",
  },
  


  // Manually add more projects here
  // Please avoid putting your projects at the very beginning or the end of the file. Instead, insert them in the middle.
  // {
  //   name: "Your Project Name",
  //   image: "./images/YourProjectImage.jpg", // Add your project image to the `images` directory
  //   description: "A brief description of your project.",
  //   usedTech: "Technologies or programming languages used.",
  //   contributorName: "Your Name",
  //   codeLink: "Link to your project's source code (GitHub, GitLab, etc.)",
  //   liveLink: "Link to the live version of your project (if available)",
  // },
];

//   export default projects;
